import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar';
import getCurrentUser from './actions/getCurrentUser';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog new wom',
  description: 'Generated by create next app',
}

export default async function RootLayout({children}: {children: React.ReactNode}) {

  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
         <ToastContainer />
         <Navbar currentUser={currentUser}/>
          {children}
       
      </body>
    </html>
  )
}


